"""
utils/detector.py — core AI image detection engine
uses CLIP model with carefully engineered text prompts
to distinguish real photographs from AI-generated images
"""
import torch
import numpy as np
from PIL import Image
from typing import Optional
from config import settings


# ─────────────────────────────────────────────────────────────
# TEXT PROMPTS
# These are the key to CLIP-based detection.
# CLIP works by comparing image embeddings to text embeddings.
# We define prompts for both "real" and "AI-generated" categories
# and measure which set the image is closer to.
# ─────────────────────────────────────────────────────────────

REAL_IMAGE_PROMPTS = [
    "a real photograph taken by a camera",
    "a genuine photo of real life",
    "a candid real world photograph",
    "a photo taken with a smartphone or DSLR camera",
    "a natural photograph with real lighting and shadows",
    "a real person photographed in real life",
    "a documentary photograph of the real world",
    "an authentic photo with natural imperfections",
    "a real landscape photograph",
    "a photo with natural grain and authentic textures",
    "a slightly blurred real photo taken by a handheld camera",
    "a low quality real photograph with motion blur and compression artifacts",
    "a noisy photograph shot in low light with realistic camera noise",
    "a compressed JPEG photo from a real smartphone camera",
    "a photograph with realistic depth of field and bokeh",
    "a real photo with natural color grading and white balance",
    "a candid street photograph with real people and motion",
    "a photograph taken with a real camera lens showing lens flare",
    "a real image with natural chromatic aberration",
    "a photograph with realistic sensor noise patterns",
    "a real photo captured in natural lighting conditions",
    "a genuine image with authentic camera metadata",
]

AI_GENERATED_PROMPTS = [
    "an image generated by artificial intelligence",
    "a synthetic image created by a neural network",
    "a fake image generated by AI like Midjourney or DALL-E",
    "an artificially generated digital artwork",
    "a deepfake or AI synthesized image",
    "an image with the uncanny valley look of AI generation",
    "a photorealistic AI generated image with perfect skin",
    "an AI generated image with overly smooth textures",
    "a synthetic face generated by a generative adversarial network",
    "a stable diffusion generated image",
    "an AI generated image with motion blur and JPEG compression artifacts",
    "an AI created photo with uniform texture and blur",
    "an image generated by machine learning algorithms",
    "a computer-generated image with artificial patterns",
    "an AI-generated picture with unnatural lighting",
    "a synthetic image with perfect symmetry and composition",
    "an artificially created image with no camera artifacts",
    "a neural network generated image with digital artifacts",
    "an AI-generated photo with unrealistic color saturation",
    "a machine-generated image with algorithmic patterns",
]


# ─────────────────────────────────────────────────────────────
# VISUAL ARTIFACT ANALYSIS PROMPTS
# Additional fine-grained prompts targeting known AI artifacts
# ─────────────────────────────────────────────────────────────

ARTIFACT_PROMPTS = {
    "skin_texture": [
        "photo with natural skin pores and imperfections",
        "photo with unnaturally smooth perfect skin",
    ],
    "background": [
        "photo with a realistic cluttered background",
        "photo with an unrealistically clean or blurry background",
    ],
    "lighting": [
        "photo with natural inconsistent lighting from one source",
        "photo with perfectly uniform artificial lighting everywhere",
    ],
    "edges": [
        "photo with natural sharp edges and focus falloff",
        "photo with suspiciously perfect edges and details",
    ],
    "symmetry": [
        "photo of a face with natural human asymmetry",
        "photo of a face with unnatural perfect symmetry",
    ],
}


class CLIPDetector:
    """
    Detects whether an image is AI-generated using CLIP embeddings.

    Strategy:
    1. Load CLIP model (vision + text encoder)
    2. Encode the image into an embedding vector
    3. Encode both real and AI-generated text prompts
    4. Compare image embedding to both prompt sets
    5. The category with higher average similarity wins
    6. Optionally run artifact analysis for detailed breakdown
    """

    def __init__(self, model_name: str):
        self.model_name = model_name
        self._model = None
        self._processor = None
        self._device = None
        self._real_embeddings = None
        self._ai_embeddings = None
        self._loaded = False

    def load(self):
        """Lazy load — only downloads model when first needed."""
        if self._loaded:
            return

        from transformers import CLIPProcessor, CLIPModel

        self._device = "cuda" if torch.cuda.is_available() else "cpu"

        self._model = CLIPModel.from_pretrained(
            self.model_name,
            cache_dir=str(settings.MODEL_CACHE_DIR),
        ).to(self._device)

        self._processor = CLIPProcessor.from_pretrained(
            self.model_name,
            cache_dir=str(settings.MODEL_CACHE_DIR),
        )

        self._model.eval()

        # Pre-compute text embeddings for all prompts
        self._real_embeddings = self._encode_texts(REAL_IMAGE_PROMPTS)
        self._ai_embeddings = self._encode_texts(AI_GENERATED_PROMPTS)

        self._loaded = True

    def _encode_texts(self, texts: list) -> torch.Tensor:
        """Encode a list of text prompts into normalized embeddings."""
        inputs = self._processor(
            text=texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
        ).to(self._device)

        with torch.no_grad():
            outputs = self._model.get_text_features(**inputs)
            embeddings = self._extract_embedding_tensor(outputs)
            # L2 normalize
            embeddings = embeddings / embeddings.norm(dim=-1, keepdim=True)

        return embeddings

    def _extract_embedding_tensor(self, outputs):
        """Extract a tensor from a CLIP model output object or return it directly."""
        if isinstance(outputs, torch.Tensor):
            return outputs
        if hasattr(outputs, "text_embeds"):
            return outputs.text_embeds
        if hasattr(outputs, "image_embeds"):
            return outputs.image_embeds
        if hasattr(outputs, "pooler_output"):
            return outputs.pooler_output
        raise ValueError(
            f"Unsupported CLIP output type: {type(outputs)}. "
            "Expected torch.Tensor or output object with text_embeds/image_embeds/pooler_output."
        )

    PROBABILITY_SCALE: float = 5.0

    def _softmax(self, raw: np.ndarray, temperature: float = 2.5) -> np.ndarray:
        raw = raw - np.max(raw)
        exp_raw = np.exp(raw * temperature)
        return exp_raw / exp_raw.sum()

    def _sigmoid_probability(self, margin: float, scale: float = None) -> float:
        scale = self.PROBABILITY_SCALE if scale is None else scale
        return 1.0 / (1.0 + np.exp(-margin * scale))

    def _aggregate_similarities(self, sims: np.ndarray, top_k: int = 5) -> float:
        """Aggregate the strongest prompt similarities for more stable probability scoring."""
        if sims.size == 0:
            return 0.0

        top_scores = np.sort(sims)[-top_k:]
        return float(np.mean(top_scores))

    def _encode_image(self, image: Image.Image) -> torch.Tensor:
        """Encode a PIL image into a normalized embedding."""
        inputs = self._processor(
            images=image,
            return_tensors="pt",
            do_resize=True,
            do_center_crop=True,
            do_normalize=True,
        ).to(self._device)

        with torch.no_grad():
            outputs = self._model.get_image_features(**inputs)
            embedding = self._extract_embedding_tensor(outputs)
            embedding = embedding / embedding.norm(dim=-1, keepdim=True)

        return embedding

    def _get_augmented_image_embedding(self, image: Image.Image) -> torch.Tensor:
        """Compute a single robust image embedding from augmented variants."""
        if not settings.USE_ROBUST_AUGMENTATION:
            return self._encode_image(image)

        from utils.image_utils import create_robust_variants

        variants = create_robust_variants(image)
        inputs = self._processor(
            images=variants,
            return_tensors="pt",
            padding=True,
        ).to(self._device)

        with torch.no_grad():
            outputs = self._model.get_image_features(**inputs)
            embeddings = self._extract_embedding_tensor(outputs)
            embeddings = embeddings / embeddings.norm(dim=-1, keepdim=True)

        return embeddings.mean(dim=0, keepdim=True)

    def predict(self, image: Image.Image) -> dict:
        """
        Run detection on a single image using multiple methods.
        """
        if not self._loaded:
            self.load()

        # Ensure RGB
        if image.mode != "RGB":
            image = image.convert("RGB")

        # Method 1: CLIP-based detection
        img_embedding = self._encode_image(image)

        real_sims = (img_embedding @ self._real_embeddings.T).squeeze(0).cpu().numpy()
        ai_sims = (img_embedding @ self._ai_embeddings.T).squeeze(0).cpu().numpy()

        max_real = float(np.max(real_sims))
        max_ai = float(np.max(ai_sims))

        # Method 2: Simple rule-based detection
        rule_based_score = self._rule_based_detection(image)

        # Combine CLIP and rule-based scores
        clip_score = max_ai / (max_ai + max_real) if (max_ai + max_real) > 0 else 0.5
        combined_score = (clip_score + rule_based_score) / 2

        # Determine final classification
        is_ai = combined_score > 0.5
        confidence = abs(combined_score - 0.5) * 2  # Scale to 0-1

        return {
            "is_ai_generated": is_ai,
            "is_uncertain": confidence < settings.MIN_CONFIDENCE,
            "ai_probability": round(combined_score, 4),
            "real_probability": round(1 - combined_score, 4),
            "confidence": round(confidence, 4),
            "avg_real_similarity": round(float(np.mean(real_sims)), 4),
            "avg_ai_similarity": round(float(np.mean(ai_sims)), 4),
            "real_scores": [round(float(s), 4) for s in real_sims],
            "ai_scores": [round(float(s), 4) for s in ai_sims],
            "top_real_prompt": REAL_IMAGE_PROMPTS[int(np.argmax(real_sims))],
            "top_ai_prompt": AI_GENERATED_PROMPTS[int(np.argmax(ai_sims))],
            "artifact_analysis": self._analyze_artifacts(img_embedding),
            "model_used": self.model_name,
            "clip_score": round(clip_score, 4),
            "rule_score": round(rule_based_score, 4),
        }

    def _rule_based_detection(self, image: Image.Image) -> float:
        """
        Simple rule-based AI detection based on image statistics.
        Returns score from 0 (real) to 1 (AI).
        """
        img_array = np.array(image, dtype=np.float32)

        # Rule 1: Check for unnatural smoothness (AI images often too smooth)
        gray = np.array(image.convert("L"), dtype=np.float32)
        laplacian = np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=np.float32)
        laplacian_var = np.var(self._convolve2d(gray, laplacian))

        # Rule 2: Check color channel correlations (AI images have different correlations)
        r, g, b = img_array[:, :, 0], img_array[:, :, 1], img_array[:, :, 2]
        rg_corr = np.corrcoef(r.flatten(), g.flatten())[0, 1]
        rb_corr = np.corrcoef(r.flatten(), b.flatten())[0, 1]
        gb_corr = np.corrcoef(g.flatten(), b.flatten())[0, 1]

        # Rule 3: Check for uniform saturation patterns
        hsv = np.array(image.convert("HSV"), dtype=np.float32)
        saturation_std = np.std(hsv[:, :, 1])

        # Combine rules (higher score = more likely AI)
        smoothness_score = min(laplacian_var / 500.0, 1.0)  # Normalize
        correlation_score = abs(rg_corr) * 0.5 + abs(rb_corr) * 0.3 + abs(gb_corr) * 0.2
        saturation_score = 1.0 - min(saturation_std / 50.0, 1.0)

        combined = (smoothness_score * 0.4 + correlation_score * 0.3 + saturation_score * 0.3)
        return float(np.clip(combined, 0, 1))

    def _convolve2d(self, a: np.ndarray, b: np.ndarray) -> np.ndarray:
        """Simple 2D convolution for edge detection."""
        a_h, a_w = a.shape
        b_h, b_w = b.shape
        out_h, out_w = a_h - b_h + 1, a_w - b_w + 1
        out = np.zeros((out_h, out_w), dtype=np.float32)
        for i in range(out_h):
            for j in range(out_w):
                out[i, j] = np.sum(a[i:i + b_h, j:j + b_w] * b)
        return out

    def _analyze_artifacts(self, img_embedding: torch.Tensor) -> dict:
        """
        Run per-artifact analysis to explain the detection.
        For each artifact type, compare image to real vs fake prompt.
        """
        results = {}

        for artifact_name, prompts in ARTIFACT_PROMPTS.items():
            real_prompt, fake_prompt = prompts
            embeddings = self._encode_texts([real_prompt, fake_prompt])
            sims = (img_embedding @ embeddings.T).squeeze(0).cpu().numpy()
            real_sim = float(sims[0])
            fake_sim = float(sims[1])

            # Which prompt is the image more similar to?
            is_suspicious = fake_sim > real_sim
            suspicion_score = (fake_sim - real_sim + 1) / 2  # normalize to 0-1

            results[artifact_name] = {
                "suspicious": is_suspicious,
                "suspicion_score": round(suspicion_score, 4),
                "real_similarity": round(real_sim, 4),
                "fake_similarity": round(fake_sim, 4),
            }

        return results


class EnsembleDetector:
    """
    Runs two CLIP models and averages their predictions.
    More accurate than a single model — reduces false positives.
    """

    def __init__(self):
        self.detector1 = CLIPDetector(settings.CLIP_MODEL)
        self.detector2 = CLIPDetector(settings.CLIP_MODEL_2)

    def load(self):
        self.detector1.load()
        if settings.USE_ENSEMBLE:
            self.detector2.load()

    def predict(self, image: Image.Image) -> dict:
        result1 = self.detector1.predict(image)

        if not settings.USE_ENSEMBLE:
            result1["ensemble"] = False
            return result1

        result2 = self.detector2.predict(image)

        # Average the combined scores from both models
        avg_ai = (result1["ai_probability"] + result2["ai_probability"]) / 2
        avg_real = (result1["real_probability"] + result2["real_probability"]) / 2
        avg_conf = (result1["confidence"] + result2["confidence"]) / 2

        is_ai = avg_ai > 0.5 and avg_conf >= settings.MIN_CONFIDENCE

        return {
            "is_ai_generated": is_ai,
            "is_uncertain": avg_conf < settings.MIN_CONFIDENCE,
            "ai_probability": round(avg_ai, 4),
            "real_probability": round(avg_real, 4),
            "confidence": round(avg_conf, 4),
            "avg_real_similarity": result1["avg_real_similarity"],
            "avg_ai_similarity": result1["avg_ai_similarity"],
            "real_scores": result1["real_scores"],
            "ai_scores": result1["ai_scores"],
            "top_real_prompt": result1["top_real_prompt"],
            "top_ai_prompt": result1["top_ai_prompt"],
            "artifact_analysis": result1["artifact_analysis"],
            "model1_result": result1,
            "model2_result": result2,
            "ensemble": True,
            "models_used": [settings.CLIP_MODEL, settings.CLIP_MODEL_2],
        }


# ─── Singleton ────────────────────────────────────────────────
detector = EnsembleDetector()
